project:
  type: website

website:
  title: "ISSS608-VAA-Project"
  navbar:
    background: primary
    search: true
    right:
      - href: index.qmd
        text: HOME
      - href: intro.qmd
        text: INTRODUCTION
      - href: story.qmd
        text: STORY
      - href: rshiny.qmd
        text: RSHINY APP
      - href: poster.qmd
        text: POSTER

format:
  html:
    theme: litera
    page-layout: full
    css: styles.css
    toc: true
    toc-title: Table of Contents

editor: visual

